### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by timqian** [timqian/sponsor.cat#17]
We are looking for a new logo for [sponsor.cat](https://sponsor.cat). Leave your design and wallet address below 😃 If your logo is selected. You will get `0.1 ETH` as a reward.

We currently don't have a DAO, but if we form one, **all participants** will get some airdropped tokens.

### Some requirements
1. Original
1. The logo should be related to `cat`, e.g. lucky cat, 招财猫
1. SVG format will be great but not a must
1. The logo should better be squared

### Useful tools
- 8 bit art: https://make8bitart.com/
- https://www.figma.com/
- Use AI to generate logos: https://beta.dreamstudio.ai/dream, https://6pen.art/

### If you don't have an ETH wallet

- https://metamask.io/
- https://token.im/

### Activity end date

We will select one from this issue at the end of January 2023

**Comment by timqian** [comment]
> example proposal

### Logo

<img src="https://user-images.githubusercontent.com/5512552/210507158-12da03ae-3a05-469c-b2b9-b8ed7ee3d457.svg" width="100"></img>

### Description
A cat paw

### Author's sponsor.cat link

https://sponsor.cat/timqian.eth

**Comment by Taolinxs** [comment]
[https://cdn-icons-png.flaticon.com/512/86/86216.png?w=996&t=st=1672888447~exp=1672889047~hmac=f61d41551b6683503083a796055e72f81f116606d80d58020e16bbae646e0ecd](url)

**Comment by Taolinxs** [comment]
![5](https://user-images.githubusercontent.com/25141730/210695070-d3c708d9-fdfd-4b35-845e-1e069437cb71.jpg)
![1](https://user-images.githubusercontent.com/25141730/210695075-9afe36f9-f3a4-4b2a-93a2-85cb50f4a6cc.png)
![2](https://user-images.githubusercontent.com/25141730/210695078-503a3b68-f33e-427a-8154-4d1be8458a95.png)
![3](https://user-images.githubusercontent.com/25141730/210695082-d24b6404-d3c7-435c-a353-a113cac52d15.png)
![4](https://user-images.githubusercontent.com/25141730/210695085-a8d0bd81-f8ee-49c6-aa95-f78cdbf5f8c4.png)
[metamask wallet]：0xCe827C6ea282dAE64a78A770652891D839A3ef28

**Comment by timqian** [comment]
@Taolinxs The logos looks good, but seems not original
<img width="1504" alt="Screen Shot 2023-01-05 at 15 27 47" src="https://user-images.githubusercontent.com/5512552/210725655-edcf624b-e231-483b-8bc1-ce3f8dc6f9eb.png">

**Comment by LONGLOGN-ROY** [comment]
<img width="460" alt="资源 9@2x" src="https://user-images.githubusercontent.com/122006233/210736528-3a660f65-bc25-4f4a-aec7-dd2623dc4f7e.png">

地址：0x5aae93ae7dbdff88aa5a1489033e1a41e05e183e

**Comment by mobilerast** [comment]
hello,

check out the designs from our designers ( [https://www.behance.net/rastmobile](https://www.behance.net/rastmobile) );

**Figma URL:**
https://www.figma.com/file/JdIAE01PVoAIgv2oJ1zEdg/sponsor.cat-Logo-Work?node-id=0%3A1&t=Pmt34AhQWAPhtDf9-0


You can see Minimalist design under the "**New Design**" tab. The rest of it is under the "**Old Design**" tab.


![timqian_9qiW4vG9](https://user-images.githubusercontent.com/58806790/212029953-2f894a3d-511e-4c26-86b6-082dd9634968.jpg)
![timqian_MVTkcYgw](https://user-images.githubusercontent.com/58806790/212029960-849ef43c-3567-439a-8d46-c9c9973aded2.jpg)

**Comment by timqian** [comment]
@mobilerast Thanks very much. These logos look awesome!
Can you also share your sponsor.cat link here?

**Comment by timqian** [comment]
@mobilerast Congrats~ Your work has been chosen as our new logo. Check your reward [here](https://sponsor.cat/0xa656536eb59e0d7a59cea505d31be70dbb0bce9f) or in your wallet

@LONGLOGN-ROY @Taolinxs Thanks for your participation!
